version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: sydmap
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "dev"]
      interval: 5s
      retries: 5
  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg://dev:dev@db:5432/sydmap
      API_PREFIX: /api
      SEED_ON_START: "1"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    environment:
      VITE_API_BASE: http://localhost:8000/api
    depends_on:
      - backend
    ports:
      - "5173:5173"
